### ISSUE TITLE
Importing from freeplane

### ISSUE THREAD

**Issue by xxpol** [insilmaril/vym#22]
Will importing maps from freeplane be possible, in the next future?
Nodes of my maps have links to local files or folders and http links. Is that possible with vym?

thank you

**Comment by insilmaril** [comment]
Freeplane import is  not really planned at the moment. Does it work using the Freemind import?

If not, maybe you can attach a simple freeplane file, which shows the links. I can have a look if this would be much effort .

**Comment by xxpol** [comment]
freemimd seems to work 
I do not use freemind so i cannot check if everything is ok 
i don't understand what you mean in the second paragraph

**Comment by insilmaril** [comment]
I was refering to your first question about " links to local files or folders and http links."  Not sure, if vym can import these at the moment, so an example map from Freemind/Freeplane might be interesting to see how it is saved there.

Yes, vym can have local links: Right click on a branch-> references-> local  to open a file dialog. Or just enter an URL (e.g. after pressing "U") with file://...   instead of http://...

**Comment by insilmaril** [comment]
Seems to work for now.
