### ISSUE TITLE
possibility to connect a child node to two parent nodes?

### ISSUE THREAD

**Issue by ghost** [insilmaril/vym#47]
Pretty much something like what is seen in the image. This is important to me because I read a lot of research papers and I want to organize the findings of each paper such that at a glance I can see what 2 different methods provide converging evidence (the methods being parent node) for an idea (a child node). So far it seems like this program can only create a strictly linear diagram. Is there a way to create a structure like in the image?
![image](https://user-images.githubusercontent.com/71096974/185718888-92193b67-fdbd-4085-a61f-48c9b9914d04.png)

**Comment by insilmaril** [comment]
Yes and No: No, because the branches have a strictly treelike structure in the underlaying data. Yes, because there are crosslinks (xlink), which can link two branches. At the moment the xlinks connect to the outer ends only of the branches, though this is going to change in future versions (3.x),  then it should be possible to make it at least look like in the picture.

**Comment by ghost** [comment]
Thanks for the response, I'll look at the xlink option and see if I can make that work
